spring:
  mail:
    username: 2156722358@qq.com
    host: smtp.qq.com
    port: 465
    password: aexlfhjpzxrxdiea
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true